language: node_js
node_js:
  - "4.0"

sudo: false

before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"
  - "npm config set spin false"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm test

notifications:
  email: false